# Generated by Django 3.0.3 on 2020-03-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth',
            field=models.IntegerField(default=2020, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=2020, verbose_name='Year'),
        ),
    ]
