# Generated by Django 3.0.3 on 2020-03-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Star', 'verbose_name_plural': 'Stars'},
        ),
    ]
